"""esquema inicial

Revision ID: efcb9afaa1d2
Revises: 
Create Date: 2026-09-14 20:58:54.591624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'efcb9afaa1d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Se maneja aparte (create/drop explícitos) porque en Postgres un Enum crea un
# tipo propio (CREATE TYPE) que op.drop_table no borra solo; en SQLite estos
# create()/drop() son no-ops (no hay tipos nativos, es VARCHAR + CHECK).
# Tiene que ser postgresql.ENUM (no sa.Enum genérico) con create_type=False:
# el create_type de un sa.Enum genérico no se propaga al adaptarlo al tipo
# nativo de Postgres (SQLAlchemy sólo respeta create_type cuando el tipo ya
# es nativo), así que con sa.Enum, Postgres igual intenta crear el tipo de
# nuevo al crear la tabla 'usuarios' (Alembic llama create_table con
# checkfirst=False, pisando el checkfirst=True del .create() explícito de
# abajo) y explota con "type rolusuario already exists".
rol_usuario_enum = postgresql.ENUM(
    'ESTUDIANTE', 'ADMIN', name='rolusuario', create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifts_id'), 'ifts', ['id'], unique=False)
    op.create_table('carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('duracion_cuatrimestres', sa.Integer(), nullable=False),
    sa.Column('ifts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ifts_id'], ['ifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carreras_id'), 'carreras', ['id'], unique=False)
    op.create_index(op.f('ix_carreras_ifts_id'), 'carreras', ['ifts_id'], unique=False)
    op.create_table('convenios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('institucion', sa.String(length=150), nullable=False),
    sa.Column('carrera_destino', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('link_info', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convenios_carrera_id'), 'convenios', ['carrera_id'], unique=False)
    op.create_index(op.f('ix_convenios_id'), 'convenios', ['id'], unique=False)
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('cuatrimestre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrera_id', 'codigo', name='uq_materia_codigo_carrera')
    )
    op.create_index(op.f('ix_materias_carrera_id'), 'materias', ['carrera_id'], unique=False)
    op.create_index(op.f('ix_materias_id'), 'materias', ['id'], unique=False)
    op.create_table('talentotech',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('nombre_curso', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('duracion', sa.String(length=50), nullable=False),
    sa.Column('link_inscripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talentotech_carrera_id'), 'talentotech', ['carrera_id'], unique=False)
    op.create_index(op.f('ix_talentotech_id'), 'talentotech', ['id'], unique=False)
    rol_usuario_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rol', rol_usuario_enum, nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_carrera_id'), 'usuarios', ['carrera_id'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('correlativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('requiere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['requiere_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('materia_id', 'requiere_id', name='uq_correlativa')
    )
    op.create_index(op.f('ix_correlativas_id'), 'correlativas', ['id'], unique=False)
    op.create_index(op.f('ix_correlativas_materia_id'), 'correlativas', ['materia_id'], unique=False)
    op.create_index(op.f('ix_correlativas_requiere_id'), 'correlativas', ['requiere_id'], unique=False)
    op.create_table('materias_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('cursando', sa.Boolean(), nullable=False),
    sa.Column('nota_parcial_1', sa.Float(), nullable=True),
    sa.Column('nota_parcial_2', sa.Float(), nullable=True),
    sa.Column('examen_final', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'materia_id', name='uq_materia_por_usuario')
    )
    op.create_index(op.f('ix_materias_usuario_id'), 'materias_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_materias_usuario_materia_id'), 'materias_usuario', ['materia_id'], unique=False)
    op.create_index(op.f('ix_materias_usuario_usuario_id'), 'materias_usuario', ['usuario_id'], unique=False)
    op.create_table('recordatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordatorios_id'), 'recordatorios', ['id'], unique=False)
    op.create_index(op.f('ix_recordatorios_materia_id'), 'recordatorios', ['materia_id'], unique=False)
    op.create_index(op.f('ix_recordatorios_usuario_id'), 'recordatorios', ['usuario_id'], unique=False)
    op.create_table('recursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recursos_id'), 'recursos', ['id'], unique=False)
    op.create_index(op.f('ix_recursos_materia_id'), 'recursos', ['materia_id'], unique=False)
    op.create_index(op.f('ix_recursos_usuario_id'), 'recursos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recursos_usuario_id'), table_name='recursos')
    op.drop_index(op.f('ix_recursos_materia_id'), table_name='recursos')
    op.drop_index(op.f('ix_recursos_id'), table_name='recursos')
    op.drop_table('recursos')
    op.drop_index(op.f('ix_recordatorios_usuario_id'), table_name='recordatorios')
    op.drop_index(op.f('ix_recordatorios_materia_id'), table_name='recordatorios')
    op.drop_index(op.f('ix_recordatorios_id'), table_name='recordatorios')
    op.drop_table('recordatorios')
    op.drop_index(op.f('ix_materias_usuario_usuario_id'), table_name='materias_usuario')
    op.drop_index(op.f('ix_materias_usuario_materia_id'), table_name='materias_usuario')
    op.drop_index(op.f('ix_materias_usuario_id'), table_name='materias_usuario')
    op.drop_table('materias_usuario')
    op.drop_index(op.f('ix_correlativas_requiere_id'), table_name='correlativas')
    op.drop_index(op.f('ix_correlativas_materia_id'), table_name='correlativas')
    op.drop_index(op.f('ix_correlativas_id'), table_name='correlativas')
    op.drop_table('correlativas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_carrera_id'), table_name='usuarios')
    op.drop_table('usuarios')
    rol_usuario_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_talentotech_id'), table_name='talentotech')
    op.drop_index(op.f('ix_talentotech_carrera_id'), table_name='talentotech')
    op.drop_table('talentotech')
    op.drop_index(op.f('ix_materias_id'), table_name='materias')
    op.drop_index(op.f('ix_materias_carrera_id'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_convenios_id'), table_name='convenios')
    op.drop_index(op.f('ix_convenios_carrera_id'), table_name='convenios')
    op.drop_table('convenios')
    op.drop_index(op.f('ix_carreras_ifts_id'), table_name='carreras')
    op.drop_index(op.f('ix_carreras_id'), table_name='carreras')
    op.drop_table('carreras')
    op.drop_index(op.f('ix_ifts_id'), table_name='ifts')
    op.drop_table('ifts')
    # ### end Alembic commands ###
